workflow:
  auto_cancel:
    on_new_commit: interruptible
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "schedule"

stages:
  - build
  - check
  - test
  - publish

.artifact-reports: &artifact-reports
  name: reports
  when: always
  paths: [ "**/build/reports" ]
  reports:
    junit: "**/build/test-results/**/TEST-*.xml"

.if-merge-request-or-main: &if-merge-request-or-main
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
  - if: $CI_PIPELINE_SOURCE == "schedule"
    when: never

.if-main: &if-main
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - if: $CI_PIPELINE_SOURCE == "schedule"
    when: never

.if-release: &if-release
  - if: '$CI_COMMIT_TAG =~ /^v\d+.\d+.\d+.*/'
  - if: $CI_PIPELINE_SOURCE == "schedule"
    when: never

build:mac:
  stage: build
  interruptible: true
  tags: [ "connect2x-mac" ]
  rules:
    - *if-merge-request-or-main
  script:
    - ./gradlew
      compileKotlin{IosArm64,IosSimulatorArm64}
      compileTestKotlin{IosArm64,IosSimulatorArm64}
      linkDebugTestIosSimulatorArm64
      --stacktrace

build:linux:
  stage: build
  interruptible: true
  tags: [ "connect2x-linux-shell" ]
  rules:
    - *if-merge-request-or-main
  script:
    - ./gradlew
      compileKotlinJvm
      compileTestKotlinJvm
      --stacktrace

check:vulnerable-dependencies:
  stage: check
  interruptible: true
  timeout: 30m
  needs: [ ]
  tags: [ "connect2x-linux-shell-small" ]
  variables:
    WITH_LOCK: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      allow_failure: true
    - if: '$CI_COMMIT_TAG =~ /^v\d+.\d+.\d+.*/'
      allow_failure: false
    - if: $CI_PIPELINE_SOURCE == "schedule"
      allow_failure: false
  artifacts:
    when: always
    reports:
      dependency_scanning: report.json
  script:
    - ./gradlew dependenciesForAll --write-locks > dependencies.txt
    - trivy repo ./ --exit-code 0 --ignorefile .trivyignore.yaml
    - trivy repo ./ --exit-code 0 --ignorefile .trivyignore.yaml --format template --template "@/usr/local/share/trivy/templates/gitlab.tpl" --output report.json
    - trivy repo ./ --exit-code 1 --ignorefile .trivyignore.yaml --severity CRITICAL

test:mac:
  stage: test
  interruptible: true
  timeout: 1h
  needs: [ "build:mac" ]
  tags: [ "saas-macos-medium-m1" ]
  artifacts: *artifact-reports
  rules:
    - *if-merge-request-or-main
  script:
    - ./gradlew iosSimulatorArm64Test --stacktrace

test:linux:
  stage: test
  interruptible: true
  timeout: 1h
  needs: [ "build:linux" ]
  tags: [ "connect2x-linux-shell" ]
  artifacts: *artifact-reports
  rules:
    - *if-merge-request-or-main
  script:
    - ./gradlew
      {jvm,testReleaseUnit}Test
      --stacktrace

publish:dev:
  stage: publish
  tags: [ "connect2x-mac" ]
  timeout: 2h
  artifacts: *artifact-reports
  rules:
    - *if-main
    - *if-release
  script:
    - ./gradlew
      publishAllPublicationsToGitLabRepository
      --stacktrace
      --no-configuration-cache

publish:release:
  stage: publish
  tags: [ "connect2x-mac" ]
  timeout: 2h
  artifacts: *artifact-reports
  rules:
    - *if-release
  script:
    - ./gradlew
      publishAndReleaseToMavenCentral
      --stacktrace
      --no-configuration-cache
